title: "Mizrhan | Data Analyst Portfolio"
description: "Python · SQL · R · KPI · Dashboard · Machine Learning"
url: "https://mizrhan.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
